# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Yu Lu 
tagline:             Grow organically via coding 
url:                 "" 
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Yu Lu
  url:               
  email:             

# Plugins
gems: [jekyll-paginate]

# Site menu
site_menu:
    About: '/about'
    Feed: '/atom.xml'
