# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Yu Lu 
tagline:             Grow organically via Coding 
url:                 http://viacoding.com 
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Yu Lu
  url:               
  email:             

# Custom vars
version:             2.0.0
github:
  repo:              
